// Auto-generated by extract_weights.py — do not edit
// Neural QDTS weight data format constants
#pragma once

#include <cstddef>
#include <cstdint>

static const int NQDTS_N_MIN = 5;
static const int NQDTS_N_MAX = 16;
static const int NQDTS_HIDDEN = 256;
static const int NQDTS_NUM_MODELS = 12;

// Byte offsets into the binary weight file for each N value
struct NQDTSModelInfo {
    int n;
    size_t offset;  // byte offset into weight data
    size_t w_in_off, b_in_off, w_h0_off, b_h0_off;
    size_t w_h1_off, b_h1_off, w_out_off, b_out_off;
};

static const NQDTSModelInfo NQDTS_MODELS[] = {
    { 5, 0, 0, 5120, 6144, 268288, 269312, 531456, 532480, 538624 },
    { 6, 538648, 538648, 544792, 545816, 807960, 808984, 1071128, 1072152, 1079320 },
    { 7, 1079348, 1079348, 1086516, 1087540, 1349684, 1350708, 1612852, 1613876, 1622068 },
    { 8, 1622100, 1622100, 1630292, 1631316, 1893460, 1894484, 2156628, 2157652, 2166868 },
    { 9, 2166904, 2166904, 2176120, 2177144, 2439288, 2440312, 2702456, 2703480, 2713720 },
    { 10, 2713760, 2713760, 2724000, 2725024, 2987168, 2988192, 3250336, 3251360, 3262624 },
    { 11, 3262668, 3262668, 3273932, 3274956, 3537100, 3538124, 3800268, 3801292, 3813580 },
    { 12, 3813628, 3813628, 3825916, 3826940, 4089084, 4090108, 4352252, 4353276, 4366588 },
    { 13, 4366640, 4366640, 4379952, 4380976, 4643120, 4644144, 4906288, 4907312, 4921648 },
    { 14, 4921704, 4921704, 4936040, 4937064, 5199208, 5200232, 5462376, 5463400, 5478760 },
    { 15, 5478820, 5478820, 5494180, 5495204, 5757348, 5758372, 6020516, 6021540, 6037924 },
    { 16, 6037988, 6037988, 6054372, 6055396, 6317540, 6318564, 6580708, 6581732, 6599140 },
};

static const size_t NQDTS_TOTAL_BYTES = 6599208;


// Declared in nqdts_weights_data.c
extern const float nqdts_weight_data[1649802];
